[package]
name = "typed-regex-derive"
version = "0.1.0"
authors = ["chriscoomber <Christopher.Coomber@metaswitch.com>"]

[dependencies]
syn = "0.11.11"
quote = "0.3.15"

[dev-dependencies]
typed-regex = {path = "../typed-regex"}

[lib]
proc-macro = true